config/routes.rb
Rails.application.routes.draw do
  resources :produits
  resources :suivis
  resources :enfants
  resources :users
  get 'admin/home'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/produit.rb
class Produit < ApplicationRecord
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  before_action :set_produit, only: %i[ show edit update destroy ]

  # GET /produits or /produits.json
  def index
    @produits = Produit.all
  end

  # GET /produits/1 or /produits/1.json
  def show
  end

  # GET /produits/new
  def new
    @produit = Produit.new
  end

  # GET /produits/1/edit
  def edit
  end

  # POST /produits or /produits.json
  def create
    @produit = Produit.new(produit_params)

    respond_to do |format|
      if @produit.save
        format.html { redirect_to admin_home_path, notice: "Produit was successfully created." }
        format.json { render :show, status: :created, location: @produit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produits/1 or /produits/1.json
  def update
    respond_to do |format|
      if @produit.update(produit_params)
        format.html { redirect_to produit_url(@produit), notice: "Produit was successfully updated." }
        format.json { render :show, status: :ok, location: @produit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1 or /produits/1.json
  def destroy
    @produit.destroy!

    respond_to do |format|
      format.html { redirect_to produits_url, notice: "Produit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produit
      @produit = Produit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produit_params
      params.require(:produit).permit(:description, :prix, :nom)
    end
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/views/produits/_form.html.erb
<%= form_with(model: produit) do |form| %>
  <% if produit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produit.errors.count, "error") %> prohibited this produit from being saved:</h2>

      <ul>
        <% produit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :prix, style: "display: block" %>
    <%= form.number_field :prix %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/produits/_produit.html.erb
<div id="<%= dom_id produit %>">
  <p>
    <strong>Description:</strong>
    <%= produit.description %>
  </p>

  <p>
    <strong>Prix:</strong>
    <%= produit.prix %>
  </p>

</div>

app/views/produits/edit.html.erb
<h1>Editing produit</h1>

<%= render "form", produit: @produit %>

<br>

<div>
  <%= link_to "Show this produit", @produit %> |
  <%= link_to "Back to produits", produits_path %>
</div>

app/views/produits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produits</h1>

<div id="produits">
  <% @produits.each do |produit| %>
    <%= render produit %>
    <p>
      <%= link_to "Show this produit", produit %>
    </p>
  <% end %>
</div>

<%= link_to "New produit", new_produit_path %>

app/views/produits/new.html.erb
<h1>New produit</h1>

<%= render "form", produit: @produit %>

<br>

<div>
  <%= link_to "Back to produits", produits_path %>
</div>

app/views/produits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produit %>

<div>
  <%= link_to "Edit this produit", edit_produit_path(@produit) %> |
  <%= link_to "Back to produits", produits_path %>

  <%= button_to "Destroy this produit", @produit, method: :delete %>
</div>