config/routes.rb
Rails.application.routes.draw do
  resources :produits
  resources :suivis
  resources :enfants
  resources :users
  get 'admin/home'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/suivi.rb
class Suivi < ApplicationRecord
  belongs_to :enfant
end

app/controllers/suivis_controller.rb
class SuivisController < ApplicationController
  before_action :set_suivi, only: %i[ show edit update destroy ]

  # GET /suivis or /suivis.json
  def index
    @suivis = Suivi.all
  end

  # GET /suivis/1 or /suivis/1.json
  def show
  end

  # GET /suivis/new
  def new
    @suivi = Suivi.new
  end

  # GET /suivis/1/edit
  def edit
  end

  # POST /suivis or /suivis.json
  def create
    @suivi = Suivi.new(suivi_params)

    respond_to do |format|
      if @suivi.save
        format.html { redirect_to root_path, notice: "Suivi was successfully created." }
        format.json { render :show, status: :created, location: @suivi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @suivi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suivis/1 or /suivis/1.json
  def update
    respond_to do |format|
      if @suivi.update(suivi_params)
        format.html { redirect_to suivi_url(@suivi), notice: "Suivi was successfully updated." }
        format.json { render :show, status: :ok, location: @suivi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @suivi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suivis/1 or /suivis/1.json
  def destroy
    @suivi.destroy!

    respond_to do |format|
      format.html { redirect_to suivis_url, notice: "Suivi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suivi
      @suivi = Suivi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def suivi_params
      params.require(:suivi).permit(:enfant_id, :jour_suivi, :temps_endormissement, :heure_endormissement)
    end
end

app/helpers/suivis_helper.rb
module SuivisHelper
end

app/views/suivis/_form.html.erb
<%= form_with(model: suivi) do |form| %>
  <% if suivi.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(suivi.errors.count, "error") %> prohibited this suivi from being saved:</h2>

      <ul>
        <% suivi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :enfant_id, value: params[:enfant] %>

  <div>
    <%= form.label :jour_suivi, style: "display: block" %>
    <%= form.date_field :jour_suivi, value: params[:jour_suivi] %>

  </div>


  <div>
    <%= form.label :temps_endormissement, style: "display: block" %>
    <%= form.number_field :temps_endormissement %>
  </div>

  <div>
    <%= form.label :heure_endormissement, style: "display: block" %>
    <%= form.datetime_field :heure_endormissement %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/suivis/_links_suivi.html.erb
<%# adapter pour prendre date de creation enfant et differencier quand suivi existe deja ou non %>    

<div class="d-flex justify-content-between align-items-center">

    <h4> suivis </h4>
    <% 7.times do |i| %>
        <% day_date = Date.today.next_day(i) %>

        <% existing_suivi = Suivi.find_by(enfant: enfant, jour_suivi: day_date) %>

        <% if existing_suivi %>
            <%= link_to "#{day_date.strftime('%d/%m/%Y')}", suivi_path(existing_suivi), class: "btn btn-sm btn-success m-1" %>
        <% else %>
            <%= link_to "#{day_date.strftime('%d/%m/%Y')}", new_suivi_path(enfant: enfant, jour_suivi: day_date), class: "btn btn-sm btn-outline-success m-1" %>
        <% end %>

    <% end %>

</div>

app/views/suivis/_suivi.html.erb
<div id="<%= dom_id suivi %>">
  <p>
    <strong>Enfant:</strong>
    <%= suivi.enfant_id %>
  </p>

  <p>
    <strong>Temps endormissement:</strong>
    <%= suivi.temps_endormissement %>
  </p>

  <p>
    <strong>Heure endormissement:</strong>
    <%= suivi.heure_endormissement %>
  </p>

</div>

app/views/suivis/edit.html.erb
<h1>Editing suivi</h1>

<%= render "form", suivi: @suivi %>

<br>

<div>
  <%= link_to "Show this suivi", @suivi %> |
  <%= link_to "Back to suivis", suivis_path %>
</div>

app/views/suivis/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Suivis</h1>

<div id="suivis">
  <% @suivis.each do |suivi| %>
    <%= render suivi %>
    <p>
      <%= link_to "Show this suivi", suivi %>
    </p>
  <% end %>
</div>

<%= link_to "New suivi", new_suivi_path %>

app/views/suivis/new.html.erb
<h1>New suivi</h1>

<%= render "form", suivi: @suivi %>

<br>

<div>
  <%= link_to "Back to suivis", suivis_path %>
</div>

app/views/suivis/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @suivi %>

<div>
  <%= link_to "Edit this suivi", edit_suivi_path(@suivi) %> |
  <%= link_to "Back to suivis", suivis_path %>

  <%= button_to "Destroy this suivi", @suivi, method: :delete %>
</div>