config/routes.rb
Rails.application.routes.draw do
  resources :produits
  resources :suivis
  resources :enfants
  resources :users
  get 'admin/home'
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/enfant.rb
class Enfant < ApplicationRecord
  belongs_to :user
end

app/controllers/enfants_controller.rb
class EnfantsController < ApplicationController
  before_action :set_enfant, only: %i[ show edit update destroy ]

  include UsersHelper

  # GET /enfants or /enfants.json
  def index
    @enfants = Enfant.all
  end

  # GET /enfants/1 or /enfants/1.json
  def show
  end

  # GET /enfants/new
  def new
    @user = User.find(current_user_id) if current_user_id

    @enfant = Enfant.new
  end

  # GET /enfants/1/edit
  def edit
  end

  # POST /enfants or /enfants.json
  def create
    @enfant = Enfant.new(enfant_params)

    respond_to do |format|
      if @enfant.save
        format.html { redirect_to root_path, notice: "Enfant was successfully created." }
        format.json { render :show, status: :created, location: @enfant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enfant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enfants/1 or /enfants/1.json
  def update
    respond_to do |format|
      if @enfant.update(enfant_params)
        format.html { redirect_to enfant_url(@enfant), notice: "Enfant was successfully updated." }
        format.json { render :show, status: :ok, location: @enfant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enfant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enfants/1 or /enfants/1.json
  def destroy
    @enfant.destroy!

    respond_to do |format|
      format.html { redirect_to enfants_url, notice: "Enfant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enfant
      @enfant = Enfant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enfant_params
      params.require(:enfant).permit(:user_id, :prenom, :birth)
    end
end

app/helpers/enfants_helper.rb
module EnfantsHelper
end

app/views/enfants/_enfant.html.erb
<div id="<%= dom_id enfant %>">

  <div class="card p-2 m-2">

    <%#= enfant.user_id %>

    <p>
      <strong>Prenom:</strong>
      <%= enfant.prenom %>
    </p>

    <p>
      <strong>Birth:</strong>
      <%= enfant.birth %>
    </p>

    <%= link_to  "show", enfant %> <hr>

  </div>

</div>

app/views/enfants/_form.html.erb
<%= form_with(model: enfant) do |form| %>
  <% if enfant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enfant.errors.count, "error") %> prohibited this enfant from being saved:</h2>

      <ul>
        <% enfant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%#= form.label :user_id, style: "display: block" %>
    <%= form.hidden_field :user_id, value: @user.id %>
  </div>

  <div>
    <%= form.label :prenom, style: "display: block" %>
    <%= form.text_field :prenom %>
  </div>

  <div>
    <%= form.label :birth, style: "display: block" %>
    <%= form.date_field :birth %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enfants/edit.html.erb
<h1>Editing enfant</h1>

<%= render "form", enfant: @enfant %>

<br>

<div>
  <%= link_to "Show this enfant", @enfant %> |
  <%= link_to "Back to enfants", enfants_path %>
</div>

app/views/enfants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enfants</h1>

<div id="enfants">
  <% @enfants.each do |enfant| %>
    <%= render enfant %>
    <p>
      <%= link_to "Show this enfant", enfant %>
    </p>
  <% end %>
</div>

<%= link_to "New enfant", new_enfant_path %>

app/views/enfants/new.html.erb
<h1>New enfant</h1>

<%= render "form", enfant: @enfant %>

<br>

<div>
  <%= link_to "Back to enfants", enfants_path %>
</div>

app/views/enfants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enfant %>

<div>
  <%= link_to "Edit this enfant", edit_enfant_path(@enfant) %> |
  <%= link_to "Back to enfants", enfants_path %>

  <%= button_to "Destroy this enfant", @enfant, method: :delete %>
</div>